### PR TITLE
[14.0][IMP] jsonifier with field name

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@gfcapalbo I've opened this one on `sunflowerit`, maybe later you can open it in OCA.

**Comment by gfcapalbo** [comment]
@thomaspaulb I was busy with lara last afternoon, this morning I had an  idea ,
perhaps _(field.string) is not the best way to fetch the string, i am afraid that if string attribute is not explicitly defined it will return nothing.... I think not , but i must verify 15 minute.

 ..... I will quickly look at how odoo/model.py  or   fields.py   does it..

**Comment by thomaspaulb** [comment]
@gfcapalbo It's currently on production and working well though.  But yes,

--> Please check if `.string` is always there

--> One thing i noticed is that when I tried to get the translation of `order_line.name` in `sale.order` in `fr_FR` language, I got the field name `Description`, while I expected something French. Maybe you can check why that is

**Comment by gfcapalbo** [comment]
@gfcapalbo OCA version has conflict -- note.

**Comment by gfcapalbo** [comment]
@thomaspaulb 

replaced by https://github.com/OCA/server-tools/pull/2668  , now that FIT/server-tools will be updated and not used as base in projects anymore. 
https://github.com/OCA/server-tools/pull/2668   needs new review and testing.

**Pull request closed without merging**
